- knock/package-lock.json
- knock/package.json
- knock/src/core/styles/global.scss
- 요구사항: 제시된 폰트, 컬러 시스템을 설정해 주세요.
- 글로벌 SCSS 파일을 생성하고 color 변수 와 shadow 믹스인 추가
- 컬러 변수 $Grayscale, $Brown, $Blue, $Yellow, $Red 추가
- 그림자 믹스인 Shadow 추가
- 사용 시 global.scss 파일을 각 scss 파일에서 import 하여 사용
- 믹스인의 경우 활용 위치에서 include 를 사용하고 param 으로 pt 값 (1~3) 전달하며 디폴트 값은 1
- https://www.figma.com/design/gU1KTGVfJrBpsECPqbwQPz/Sprint-8-2?node-id=1-916&m=dev 에서 Foundation 참고
- 각 변수 및 믹스인과 피그마 요구사항 비교 및 확인
- scss 파일 import 방법과 변수 및 믹스인 사용 방법 확인
- 폰트 시스템 추가 필요 여부 및 방법 확인
Resolves #14
> Feature 14 글로벌css추가

- knock/public/index.html
- reset CSS 추가
- index.html 파일 내 reset CSS CDN Link 태그 추가
- restore #20 
- [reset CSS CDN](https://www.jsdelivr.com/package/npm/reset-css)
> Feature 18 reset css추가

- knock/src/core/styles/icon/icon.module.scss
- knock/src/core/ui/Icon/Icon.tsx
- icon 컴포넌트 로직 추가
- icon 컴포넌트 이미지경로 및 설명 props로 추가했습니다.
이외에 추가해야하는 부분 있으면 피드백 부탁드립니다.
> Feature 9 icon컴포넌트추가

- knock/src/core/styles/input.module.scss
- knock/src/core/ui/Input/Input.tsx
input 컴포넌트 추가
input 컴포넌트 추가
_집중 리뷰 부분 작성_
> Feature 8 공통 input컴포넌트 추가

- knock/src/core/styles/Textarea.module.scss
- knock/src/core/ui/Textarea/Textarea.tsx
공통 Textarea 컴포넌트 추가
Textarea 컴포넌트 추가
props로 placeholder ,value,id,name 
onChange,onKeyDown 이벤트 핸들러 받기
- default placeholder
- focus
- enterd text
피드백해야할 사항 알려주세요~
> Feature 12 공통 Textarea 컴포넌트 추가

- knock/package-lock.json
- knock/package.json
- knock/src/core/ui/buttons/FloatingButton/FloatingButton.module.scss
- knock/src/core/ui/buttons/FloatingButton/FloatingButton.tsx
- knock/src/pages/MainPage/MainPage.tsx
공통 Floating버튼 컴포넌트 추가
children prop 에 버튼 내용 전달
Resolves #6
> Feature 6 공통 Floating버튼 컴포넌트 추가 #6

- knock/src/core/styles/badge.module.scss
- knock/src/core/ui/Badge/Badge.tsx
- 공통 Badge 컴포넌트 추가
-  Badge.tsx 컴포넌트 작성
- Badge.scss 생성
- status="answer" 또는  "unanswer" 로 prop 을 받아서 처리 
- Badge.module.scss 에  height, weidth 부분을 잘 처리했는지 확인 부탁드립니다.
- 컴포넌트를 잘 구상했는지 확인 부탁드립니다.
Resolves #31
> Feature 31 공통 Badge 컴포넌트 추가

- knock/src/core/types/api/Request.ts
- knock/src/core/types/api/Response.ts
- knock/src/lib/api/APIHandler.ts
- knock/src/lib/api/Answers.ts
- knock/src/lib/api/Questions.ts
- knock/src/lib/api/Subject.ts
- API 도메인 별 함수 정리
- Subjects / Questions / Answers 도메인 API 정리
- Request / Response type 정리
- apiHandler class 선언
- 사용하실 때 불편할 것 같은 점을 알려주세요 😆
- 피드백 주시면 감사합니다 
- 타입 다 정의해놔서 마우스 hover 을 통해 타입 확인하고 사용하시면 됩니다 😄
> Feature 44 api파일추가

- knock/src/core/styles/dropdown.module.scss
- knock/src/core/ui/Dropdown/Dropdown.tsx
- knock/src/core/ui/Dropdown/DropdownContent.tsx
- 버튼 스타일 커스텀할 수 있도록 수정
- 드랍다운 내용 줄바꿈 수정
- 버튼 정렬에 의한 드랍다운 이외에도 사용할 수 있도록 커스텀 가능하게 만들었습니다
- 드랍다운 내용이 길어지면 줄바꿈으로 요소가 이상해지는 버그를 수정했습니다
- 추가할 사항이나 고쳐야할 부분 피드백 부탁드립니다..
close #53
> Fix 53 dropdown외곽선수정

- knock/src/core/styles/input.module.scss
- knock/src/core/ui/Input/Input.tsx
input focus로직 scss로 구현수정
input focus, blur이벤트와 state를 사용해서 style을 바꾸던 로직을 지우고
scss로 구현했습니다.
Resolves #57
> Fix 57 Input컴포넌트 focus로직 scss로 구현 수정

- knock/src/components/Question/Question.module.scss
- knock/src/components/Question/Question.tsx
- knock/src/lib/hooks/useElapsedTime.ts
feed card안의 question컴포넌트 추가
feed card안의 question컴포넌트 추가
props로 질문내용과 질문 저장시간을 가져와 사용
질문저장 경과시간 계산하는 hook 추가
저장시간으로 useElapsedTime hook에서 저장경과시간 계산후 사용 
피드백 부탁드려요~
Resolves #62
> Feature 62 question컴포넌트추가

- knock/src/core/styles/toast.module.scss
- knock/src/core/ui/Toast/Toast.tsx
- 공통 toast 컴포넌트 추가
파일생성
- src/core/styles/toast.module.scss
- src/core/ui/Toast/Toast.tsx 
- Toast 컴포넌트를 호출하면 setTimeout함수를 통해 2초동안
메세지를 출력합니다.
- 틀린것이 있는지 확인 부탁드립니다.
- #40
> Feature 40 공통 toast 컴포넌트 추가 

- knock/package-lock.json
- knock/src/core/ui/CommonIcon/icon.tsx
- knock/src/pages/ModalPage.tsx
- knock/src/pages/modalPage.scss
modal 컴포넌트 추가
- 모달 관련 ui 제작
- api 추후 연동 예정
- 잘못된 부분이 없는지 피드백 부탁드립니다.
> Feature 60 modalPage 컴포넌트 ui 추가

- knock/src/components/Profile/Profile.module.scss
- knock/src/components/Profile/Profile.tsx
프로필 컴포넌트 UI 만 만들었습니다.
이후에 작업을 더 하겠습니다.
-
-scss 에서 틀린게 없는지 확인 부탁드립니다.
#79
> Feature 79 프로필 컴포넌트 추가

- knock/src/components/Answer/Answer.module.scss
- knock/src/components/Answer/Answer.tsx
- knock/src/components/AnswerContent/AnswerContent.module.scss
- knock/src/components/AnswerContent/AnswerContent.tsx
- knock/src/components/AnswerForm/AnswerForm.module.scss
- knock/src/components/AnswerForm/AnswerForm.tsx
- knock/src/components/AnswerModification/AnswerModification.module.scss
- knock/src/components/AnswerModification/AnswerModification.tsx
- knock/src/components/AnswerRejection/AnswerRejection.module.scss
- knock/src/components/AnswerRejection/AnswerRejection.tsx
answer컴포넌트 추가
피드카드 컴포넌트 안에 들어가는 answer컴포넌트 추가
리뷰 부탁드립니다.
resolves #73
> Feature 73 피드 Answer컴포넌트 추가 

- knock/src/App.tsx
- knock/src/components/FeedCard/FeedCard.module.scss
- knock/src/components/FeedList/FeedList.tsx
- knock/src/core/styles/answerPage.module.scss
- knock/src/lib/hooks/feed/useQuestionList.tsx
- knock/src/pages/AnswerPage.tsx
- 답변하기 초기 페이지 추가
- 답변하기 초기 페이지 추가
- 페이지 레이아웃 정도 잡아놓은 상태입니다. 감안해서 리뷰 부탁드립니다.
- 추가 개발할 것이 많이 남아있습니다. 현재는 페이지 테스트를 위한 코드가 많이 담겨있습니다. 감안해서 리뷰 부탁드립니다.
#65
> Feature 65 답변하기 초기 페이지 추가

- knock/src/lib/hooks/useSubmitQuestion.ts
- knock/src/pages/ModalPage.tsx
- knock/src/pages/modalPage.scss
- modal 컴포넌트 api 추가
- modal 컴포넌트 POST API 추가
- 잘못된 부분 없는지 피드백 부탁드립니다..!
> Feature: modal컴포넌트 api 추가

- knock/src/lib/hooks/useSubmitQuestion.ts
- knock/src/pages/ModalPage.tsx
- knock/src/pages/modalPage.scss
- modal 페이지 피드백 수정
- "질문하기" 버튼위치 중간 -> 오른쪽 수정
- subjectId type : number -> number | string 타입 수정
- scss 파일 이름 수정
> Fix 77 modal 컴포넌트 피드백 수정

- knock/src/components/Profile/Profile.module.scss
- knock/src/components/Profile/Profile.tsx
- 피드 페이지 작업을 위해서 기능 없이 ui 만 수정해서 올립니다
- 피드 페이지 프로필 이미지 radius 수정 
- 반응형 설정
- 수정사항 피드백해주시면 감사합니다 👍 
close #99
> Fix 피드 페이지 프로필 이미지 수정

- knock/src/core/styles/dropdown.module.scss
- knock/src/core/ui/Dropdown/Dropdown.tsx
- knock/src/core/ui/Dropdown/DropdownContent.tsx
- knock/src/lib/hooks/useCloseRef.ts
- Dropdown 추가기능 개발
- hook을 이용한 리팩토링
- 외부 클릭 시 드랍다운이 닫히는 기능 추가
- 드랍다운 애니메이션 추가
- useCloseRef 활용하여 UI / 로직 분리
- 드랍다운 기능 피드백 부탁드립니다
- 미리보기에서 사용가능합니다
Closes #108
> Feature 108 dropdown추가기능

- knock/src/lib/hooks/useLoscalStorageUserInfo.ts
- 로컬스토리지 기능 수정
- 선언 전 사용으로 인한 오류 수정
Close #122
> Fix 로컬스토리지 기능 수정 

- knock/src/components/QuestionList/QuestionListMain.tsx
- knock/src/components/QuestionList/QuestionListPagination.tsx
- knock/src/components/feed/FeedCard/FeedCard.tsx
- knock/src/core/ui/Dropdown/Dropdown.tsx
- knock/src/core/ui/Dropdown/DropdownContent.tsx
- 멘토링 사항 반영
- 요소 리스트를 받는 방식 변경
- 요소 선택 방식 변경
- 요소 리스트 방식을 `React.ReactNode[]`  -> `Objtect`로 변경했습니다
- Object
- `selected`-`string`: 요소를 선택했을 때 사용할 구분자
- `content`-`string`: 드랍다운에 들어갈 내용
- `iconSource` - `string`(optional): 아이콘을 사용할 때 넣는 아이콘 요소
- 피드백 해주시면 감사합니다 😊
Closes #118
> Fix 118 질문 목록 페이지 드랍다운 수정

- knock/src/lib/api/APIHandler.ts
- api 오류 메세지 구체화
- 기존 api 오류 메세지 수정
- 404번 에러
- detail 메세지가 있는 경우: detail 메세지 출력
- detail 메세지가 없는 경우: `요청하신 주소를 찾을 수 없습니다. 주소를 확인해주세요.` 메세지 출력
- 그외 에러
- `알 수 없는 에러입니다 네트워크 탭을 확인해주세요` 메세지 출력
#. 리뷰 요구사항
- 추가할 사항 혹은 피드백 해주시면 감사합니다  😊
Closes #125
> Fix 125 api오류메세지수정

- knock/src/components/MainPageInput/MainPageInput.tsx
- knock/src/components/MainPageInput/mainPageInput.module.scss
- knock/src/core/styles/input.module.scss
메인페이지input컴포넌트추가
```
<MainPageInput
onSubmit={handleSubmit}
placeholder="이름을 입력하세요"
submitButtonText="질문 받기"
/> 
```
이렇게 사용
- 
-api 보내는 부분 확인부탁드립니다.
-
클릭을 하면 이런 에러가 나지만 홈페이지를 만들고 처리하겠습니다.
#74
> Feature 74 메인페이지input컴포넌트추가

- knock/src/components/MainPageInput/MainPageInput.tsx
- MainPage 수정
- import 최신파일경로 로 수정
- API 처리부분 수정
- 불필요한 코드가 있는지 확인 부탁드립니다.감사합니다.
- #91
> Feature 91 Main page수정

- knock/src/components/Modal/ModaCreateQuestion.module.scss
- knock/src/components/Modal/ModaCreateQuestion.tsx
- knock/src/core/styles/Textarea.module.scss
- knock/src/core/ui/Modal/CommonModal.module.scss
- knock/src/core/ui/Modal/CommonModal.tsx
- knock/src/pages/CreateQuestionPage.module.scss
- knock/src/pages/CreateQuestionPage.tsx
- 모달창 레이아웃 수정
- 모달 질문하기 버튼 수정
- "질문작성하기"버튼 모바일에서 "질문작성"으로 text변경 수정
- 모달창 레이아웃 틀어짐 수정
- 모달창 모바일 버전으로 반응형 레이아웃추가
> fix: 모달 레이아웃 수정

- knock/src/components/SubjectList/SubjectCard.tsx
- knock/src/components/SubjectList/SubjectCardList.module.scss
- knock/src/core/styles/usercard/UserCard.module.scss
- 반응형 수정
- 긴 이름 축약 기능 추가
- 반응형 수정
- 긴 이름 축약 기능 추가
- 수정할 사항이 더 있다면 말씀해주세요 😄
Closes #126
> Feature 126 질문목록페이지 UI기능추가

- knock/src/components/Question/Question.module.scss
- knock/src/components/Question/Question.tsx
- knock/src/components/feed/Answer/Answer.tsx
- knock/src/components/feed/AnswerContent/AnswerContent.module.scss
- knock/src/components/feed/AnswerContent/AnswerContent.tsx
- knock/src/components/feed/AnswerModification/AnswerModification.module.scss
피드카드 답변하기 context 더보기 기능 및 버튼 추가
answer컴포넌트  미사용 import 삭제
피드카드 답변하기 context 더보기 기능 및 버튼 추가
content text 6줄 넘어가면 더보기 버튼 생성 
피드백 부탁드립니다
close #142
> Feature 142 피드답변하기Context더보기기능추가

- knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
- 카카오톡 공유하기 버튼 로직 수정
- 이름 사진 안나오는 버그 수정
- 피드백 부탁드립니다
Closes #151
> Fix 카카오톡 공유하기 오류 수정

- knock/public/index.html
- knock/src/components/Question/Question.tsx
- knock/src/components/SubjectList/SubjectCard.tsx
- knock/src/core/styles/dropdown.module.scss
- knock/src/core/ui/DarkModeBtn/DarkModeBtn.tsx
- knock/src/lib/hooks/subjectList/useSubjectList.ts
- knock/src/lib/hooks/useSubmitQuestion.ts
- 최종배포전 오류 수정
- dummy.txt 삭제
- console.log 삭제
- dropdown 오류 수정
Closes #154
> Fix 154 최종배포 전 오류 수정

- knock/src/components/feed/AnswerForm/AnswerForm.module.scss
- knock/src/components/feed/AnswerModification/AnswerModification.module.scss
- knock/src/components/feed/AnswerProfile/AnswerProfile.tsx
- knock/src/components/feed/ConfirmModal/ConfirmModal.tsx
- knock/src/core/ui/buttons/UButton/UButton.module.scss
- 답변페이지 피드백 추가 수정
- 개선점 있을지 리뷰 부탁드립니다
> Fix 147 답변페이지 피드백 추가 수정

- knock/src/components/Question/Question.module.scss
- knock/src/components/Question/Question.tsx
- knock/src/components/feed/AnswerContent/AnswerContent.module.scss
- knock/src/components/feed/AnswerContent/AnswerContent.tsx
- knock/src/pages/PostPage.module.scss
- 개별피드페이지 피드백 수정
- 개별피드페이지 배너 크기 변경
- 질문, 답변 content 더보기 버튼 수정
- 피드백해주세요
close #157
> fix: 개별피드페이지 피드백 수정 #157

- knock/src/components/Profile/Profile.tsx
- knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
- knock/src/core/ui/buttons/ShareButtons/ShareButtons.tsx
- 카카오 공유하기 메세지 변화 추가
- 카카오 공유하기 기능
- 내 피드 페이지 공유 시 : OOO님께서 질문을 요청하셨어요!
- 다른 피드 페이지 공유 시 : OOO님께 질문을 해보세요!
- 피드백 부탁드립니다
Closes #162
> Feature 162 카카오 공유하기 내 페이지 / 다른 페이지 공유 시 메세지 변화 추가

- knock/src/core/styles/answerPage.module.scss
- knock/src/pages/AnswerPage.tsx
- 답변페이지 background image 수정 
- Image 컴포넌트 사용에서 css background-image 로 전환했습니다
- 이견 있다면 말씀 부탁드립니다
- 요구사항 충족하도록 수정했습니다
Resolves#147
> Fix 147 답변페이지 background image 수정 

- knock/src/lib/hooks/subjectList/useSubjectListQuery.ts
- 질문 목록 페이지 정렬 오류 수정
- URL 오류로 인한 질문 목록 페이지 정렬 오류 수정
Close #165
> fix: 질문목록페이지 정렬 오류 수정 #165

- knock/src/lib/hooks/subjectList/useSubjectList.ts
- 질문목록페이지 초기값 설정 누락으로 인한 스켈레톤 UI 버그 수정
- 초기값 설정 누락으로 인한 스켈레톤 UI 버그 수정
Close #168
> fix: 질문목록페이지 스켈레톤 UI 버그 수정 #168

- knock/src/App.tsx
- knock/src/core/ui/MetaTags/MetaTags.tsx
- knock/src/pages/AnswerPage.tsx
- knock/src/pages/PostPage.tsx
- 공통 메타태그 수정
- 메타 태그 컴포넌트 타이틀, 이미지 수정
- 질문, 답변 페이지 메타 태그 타이틀 프롭 추가
- 리뷰 부탁드립니다
Resolves #172
> Feature 172 공통 메타태그 수정

- knock/src/lib/hooks/subjectList/useSubjectList.ts
- 질문 목록 페이지 스켈레톤 UI 요소 개수 다른 것 수정
- isLoading일 때 default 요소 개수 수정
Close #168
> fix 168 질문 목록 페이지 스켈레톤 UI 요소 개수 오류 수정

- knock/package-lock.json
- knock/package.json
- knock/src/components/MainPageInput/MainPageInput.tsx
- knock/src/components/MainPageInput/mainPageInput.module.scss
- knock/src/components/Question/Question.module.scss
- knock/src/components/Question/Question.tsx
- knock/src/components/SubjectList/SubjectListHeader.module.scss
- knock/src/components/SubjectList/SubjectListHeader.tsx
- knock/src/components/SubjectList/SubjectModalContent.module.scss
- knock/src/components/SubjectList/SubjectModalContent.tsx
- knock/src/components/feed/AnswerContent/AnswerContent.module.scss
- knock/src/components/feed/AnswerContent/AnswerContent.tsx
- knock/src/components/feed/FeedList/FeedList.tsx
- knock/src/core/styles/usercard/UserCard.module.scss
- knock/src/core/ui/UserCard/UserCard.tsx
- knock/src/pages/MainPage.module.scss
- knock/src/pages/MainPage.tsx
공통아이콘수정
react-icons 라이브러리 사용하여 icon 수정
Closes #173
> Fix 173 공통아이콘수정

- knock/src/components/feed/FeedList/FeedList.module.scss
> Fix 피드 피드리스트 패딩 수정
